### ISSUE TITLE
Wrong number of students after writing vastapalaute

### ISSUE THREAD

**Issue by pllk** [UniversityOfHelsinkiCS/palaute#1382] opened 2024-10-26 08:52 UTC
Before writing vastapalaute I could see the feedback given by students. There were more than five students who had given feedback. However, after writing vastapalaute the system doesn't show the feedback and claims that the number of students is less than five.

![image](https://github.com/user-attachments/assets/b6ed0af2-afd8-4c86-bb57-7ec643a85045)

The system also shows that 29 out of 0 students have given feedback which is weird. The correct number of students is 87.

![image](https://github.com/user-attachments/assets/ae49bb99-68ca-4043-a77e-cb082fa1846c)

I'm not sure if this is actually related to writing vastapalaute, but at least the bug appeared after writing vastapalaute.

**Comment by pllk** [comment] 2024-10-26 08:54
A similar issue: #1315

**Comment by HRemonen** [comment] 2024-10-30 06:02
Duplicate of #1315, as you mentioned. Closing, but leaving as a reference.

**Closed by HRemonen** 2024-10-30 06:02 UTC
