### ISSUE TITLE
SISU groups vs. Norppa groups - fix difference in behaviour

### ISSUE THREAD

**Issue by tttriple** [UniversityOfHelsinkiCS/palaute#1380] opened 2024-10-24 08:16 UTC
SISU:
student can choose between one to many groups

EXAMPLE:
https://sisu.helsinki.fi/teacher/role/staff/teaching/course-unit-realisations/view/hy-opt-cur-2425-68feac15-9b90-4ec7-ad91-0275f97e5f5b/enrolment/enrolled

NRPP:
student can choose only one group

EXAMPLE:
https://norppa.helsinki.fi/targets/82145369/edit

This should consisent,

**Comment by HRemonen** [comment] 2024-10-24 08:32
Duplicate of #1379

**Closed by HRemonen** 2024-10-24 08:32 UTC
